ecc_theme_gov.settings:
  type: config_object
  label: 'ECC Theme Gov settings'
  mapping:
    localgov_base_remove_css:
      type: boolean
      label: 'Remove CSS libraries from base theme.'
    localgov_base_remove_js:
      type: boolean
      label: 'Remove JS libraries from base theme.'
    localgov_base_add_unpublished_background_colour:
      type: boolean
      label: 'Add background colour to unpublished content.'
    localgov_base_add_draft_note_to_unpublished_content:
      type: boolean
      label: 'Add "[Draft]" to title of unpublished content.'
    localgov_base_add_archived_note_to_archived_content:
      type: boolean
      label: 'Add "[Archived]" to title of archived content.'
